### ISSUE TITLE
Comment

### ISSUE THREAD

**Issue by PowerPress** [stryngs/scripts#1]
Hey cool scripts! I wanted to message you about AirPwn but it looks like issues are disabled on that repo. Awesome work continuing the project. Any plans to release some detailed documentation? The Regular AirPwn docs are lacking and dont mention any of the new features. How exactly does your beef hooks integrate with Beef? I assume you would just run been and change the IP in your hooks to your local IP and your ready to rock? Will all beef features work or just the ones you wrote hooks for? Also what is the benefit of grabbing all the cookies? I couldnt really find any documentation on the benefits of that and how it relates to this project? Can this bypass SSL?

Thanks

**Comment by stryngs** [comment]
Hi PowerPress,

Not sure if I ever responded, and I do owe you a response.  You still 
interested in this?

--stryngs

**Comment by PowerPress** [comment]
Yes please

**Comment by stryngs** [comment]
@PowerPress Wow, evidently we both never followed up.  Are you interested in spinning this issue back up?  Would love the feedback.

**Comment by stryngs** [comment]
@PowerPress feel free to open any issues you want on [airpwn-ng](https://github.com/ICSec/airpwn-ng)
